### ISSUE TITLE
Unit test exercise - unit test

### ISSUE THREAD

**Issue by Kirit-Singh** [Kirit-Singh/BME547_Classwork_Spring2023#13]
Completion of unit test function for xy_calculator
[test_xy_calculator](https://github.com/Kirit-Singh/BME547_Classwork_Spring2023/blob/unit_testing_exercise/test_xy_calculator.py)

**Comment by dward2** [comment]
Your unit tests look good.  The only issue is that you have two functions with the same name:  `test_line_checker`.  Python will only run the second of the two functions and so the first function will never run.  Make sure that all of your functions have unique names.  For example, I might rename these two functions to be `test_line_checker_true` and `test_line_checker_false`.  Otherwise, everything looks good.

**Comment by Kirit-Singh** [comment]
Thank you for your feedback! I'll go ahead and update the code to name the two functions differently
